services:
  frontend-production:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_ZIPCODE_API: ${FRONTEND_ZIPCODE_API}
          VITE_URL_API: ${FRONTEND_URL_API}
    container_name: frontend-production
    ports:
      - "8080:80"
    restart: unless-stopped
